version: '3'
services:
  teachers:
    build:
      context: .
      dockerfile: Dockerfile.learner-app
    ports:
      - '3001:3001'
      - '4101:4101'
      - '4109:4109'
    environment:
      - NODE_ENV=production
