version: '3'
services:
  admin-app-repo:
    build:
      context: .
      dockerfile: Dockerfile.admin-app
    ports:
      - '3032:3002'
      - '4104:4104'
      - '4109:4109'
    environment:
      - NODE_ENV=production
